export const LOGIN_ROUTE = '/login'
export const ADMIN_ROUTE = '/admin'
export const STORAGE_ROUTE = '/storage'
export const USER_ROUTE = '/user'
export const ORDER_ROUTE = '/order'
export const DEVICE_ROUTE = '/device'
export const REQUEST_ROUTE = '/req'
export const USER_PROFILE_ROUTE = '/user/profile'
